### ISSUE TITLE
The game crashed whilst registering texture. Error: java.lang.IllegalArgumentException: Invalid texture size: 8x0

### ISSUE THREAD

**Issue by TenKotowsky** [dzwdz/chat_heads#58]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2023-07-16 13:55:00
Description: Registering texture

java.lang.IllegalArgumentException: Invalid texture size: 8x0
	at net.minecraft.class_1011.<init>(class_1011.java:58)
	at net.minecraft.class_1011.<init>(class_1011.java:53)
	at dzwdz.chat_heads.ChatHeads.extractBlendedHead(ChatHeads.java:209)
	at net.minecraft.class_1046.handler$zjo000$chat_heads$chatheads$registerBlendedHeadTexture(class_1046.java:538)
	at net.minecraft.class_1046.method_4534(class_1046.java)
	at net.minecraft.class_1046.method_4625(class_1046.java:99)
	at net.minecraft.class_1060.method_24303(class_1060.java:97)
	at net.minecraft.class_1060.method_4616(class_1060.java:69)
	at net.minecraft.class_1071.method_4651(class_1071.java:78)
	at net.minecraft.class_1071.method_22819(class_1071.java:121)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at net.minecraft.class_1071.method_4655(class_1071.java:119)
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(RenderSystem.java:226)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:213)
	at net.minecraft.class_1041.method_15998(class_1041.java:288)
	at net.minecraft.class_310.method_1523(class_310.java:1241)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1011.<init>(class_1011.java:58)
	at net.minecraft.class_1011.<init>(class_1011.java:53)
	at dzwdz.chat_heads.ChatHeads.extractBlendedHead(ChatHeads.java:209)
	at net.minecraft.class_1046.handler$zjo000$chat_heads$chatheads$registerBlendedHeadTexture(class_1046.java:538)
	at net.minecraft.class_1046.method_4534(class_1046.java)
	at net.minecraft.class_1046.method_4625(class_1046.java:99)
	at net.minecraft.class_1060.method_24303(class_1060.java:97)
	at net.minecraft.class_1060.method_4616(class_1060.java:69)
	at net.minecraft.class_1071.method_4651(class_1071.java:78)
	at net.minecraft.class_1071.method_22819(class_1071.java:121)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at net.minecraft.class_1071.method_4655(class_1071.java:119)
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(RenderSystem.java:226)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:213)

-- Resource location being registered --
Details:
	Resource location: minecraft:capes/17f76a23ff4d227a94ea3d5802dccae9f2ae9aa9
	Texture object class: net.minecraft.class_1046
Stacktrace:
	at net.minecraft.class_1060.method_24303(class_1060.java:97)
	at net.minecraft.class_1060.method_4616(class_1060.java:69)
	at net.minecraft.class_1071.method_4651(class_1071.java:78)
	at net.minecraft.class_1071.method_22819(class_1071.java:121)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at net.minecraft.class_1071.method_4655(class_1071.java:119)
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(RenderSystem.java:226)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:213)
	at net.minecraft.class_1041.method_15998(class_1041.java:288)
	at net.minecraft.class_310.method_1523(class_310.java:1241)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, file/swetrowe tekstury 2.3 - 1.20.x, replaymod_lang, essential
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2413)
	at net.minecraft.class_310.method_1514(class_310.java:821)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 943823704 bytes (900 MiB) / 1509949440 bytes (1440 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 2060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1e89
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3640
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37817.46
	Virtual memory used (MB): 22319.46
	Swap memory total (MB): 21504.00
	Swap memory used (MB): 1097.51
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		additionz: AdditionZ 1.1.10
		adorn: Adorn 5.0.0+1.20.1
		ambientsounds: AmbientSounds 5.2.20
		appleskin: AppleSkin 2.5.0+mc1.20
		architectury: Architectury 9.1.10
		awesomedungeonend: Awesome dungeon the end 3.1.1
		awesomedungeonnether: Awesome dungeon nether 3.1.1
		awesomedungeonocean: Awesome dungeon edition ocean 3.3.0
		bedspreads: Bedspreads 6.2.0+1.20.1
		beekeeperhut: Friends&Foes - Beekeeper Hut 1.3.0
		betterarcheology: Better Archeology 1.0.2
		betterstats: Better Statistics Screen 2.10.3+1.20.1
			tcdcommons: TCD Commons API 2.10.2+1.20.1
		biomemakeover: Biome Makeover 1.20.1-1.10.2
			taniwha: Taniwha 1.20.0-5.1.1
		blossom: Blossom 1.0.7
		cat_jam: cat_jam 1.1.3
		chat_heads: Chat Heads 0.10.17
		clickadv: Clickable Advancements Mod 1.20.1-3.2
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 6.65
		connectivity: Connectivity Mod 1.20.1-4.4
		controlling: Controlling For Fabric 12.0.2
		creativecore: CreativeCore 2.10.28
			net_minecraftforge_eventbus: eventbus 6.0.3
		dawn: Dawn API 5.0.0
			terraform-shapes-api-v1: Terraform Shapes API (v1) 7.0.1
			terraform-wood-api-v1: Terraform Wood API (v1) 7.0.1
		easyanvils: Easy Anvils 8.0.0
		elementa: Elementa 590
		emojitype: Emoji Type 2.1.0+1.20
		emotecraft: Emotecraft 2.2.7-b.build.50
			bendy-lib: Bendy api 4.0.0
			player-animator: Player Animator 1.0.2-rc1+1.20
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20
		essential: Essential 12933+deploy-staging+gf941de5ac
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.2.0
		fabric-api: Fabric API 0.85.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.29+b04edc7a77
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.34+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.39+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.0+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.32+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.11+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.49+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.61+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.8+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.3+b3afc78b77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.1.12+b3afc78b77
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.51+b3afc78b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.21+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.0+b3afc78b77
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.61+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.26+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.8+40e50c4677
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.20+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.38+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.42+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.6+b3afc78b77
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.48+b3afc78b77
			fabric-models-v0: Fabric Models (v0) 0.3.35+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.8+b3afc78b77
			fabric-networking-v0: Fabric Networking (v0) 0.3.48+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.0+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.0+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.18+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.6+b3afc78b77
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.0+c154966e77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.0+c154966e77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.44+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.33+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.26+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.47+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.6+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.8+e3d6ed2577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.6+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.27+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.3+43a3fedd77
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.2.0+b3afc78b77
		fabric-language-kotlin: Fabric Language Kotlin 1.9.5+kotlin.1.8.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.20.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.1
		fabricloader: Fabric Loader 0.14.21
		fallingleaves: Falling Leaves 1.15.1+1.20.1
		fancydyes: Fancy Dyes 2.0.0
		ferritecore: FerriteCore 6.0.0
		flowerymooblooms: Friends&Foes - Flowery Mooblooms 1.1.0
		forgeconfigapiport: Forge Config API Port 8.0.0
		forgottengraves: Forgotten Graves 1.20.1-3.2.0
		fpsdisplay: FPS-Display 1.5.0+1.20
		fpsreducer: FPS Reducer 1.20-2.5
		friendsandfoes: Friends&Foes 1.9.2
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.8
		geodes: More Geodes 1.8.2
		geophilic: Geophilic v2.0.0-mc1.20u1.20.1
		harvestwithease: Harvest with ease 7.0.0.2
		immediatelyfast: ImmediatelyFast 1.1.16+1.20.1
			net_lenni0451_reflect: Reflect 1.2.1
		inventoryhud: Inventory HUD + 3.4.15
		iris: Iris 1.6.4
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		jade: Jade 11.2.2
		java: OpenJDK 64-Bit Server VM 17
		libraryferret: Library ferret 4.0.0
		mavapi: More Axolotl Variants API 1.1.1
		mavm: More Axolotl Variants Mod 1.2.4
		memoryleakfix: Memory Leak Fix 1.1.1
		minecraft: Minecraft 1.20.1
		modmenu: Mod Menu 7.1.0
		morechathistory: MoreChatHistory 1.1.1
		notenoughanimations: NotEnoughAnimations 1.6.4
		nutritious-feast: Nutritious Feast 1.7.1
		offlineskins: OfflineSkins 1.20.1-v1a-fabric
		ok-boomer: Ok Boomer 0.1.2+1.20
		org_jetbrains_annotations: annotations 13.0
		owo: oωo 0.11.1+1.20
			blue_endless_jankson: jankson 1.2.2
		oxidized: Oxidized 1.8.2
			saflib: SafLib 1.0.32
		promenade: Promenade 4.1.0
			biolith: Biolith 1.0.0-alpha.7
				terraform-surfaces-api-v1: Terraform Surfaces API (v1) 7.0.0-beta.1
		puzzleslib: Puzzles Lib 8.0.7
		reeses-sodium-options: Reese's Sodium Options 1.5.1+mc1.20-build.74
		regenerations: Regenerations? 1.1.0
		replaymod: Replay Mod 1.20.1-2.6.13
		replayvoicechat: Replay Voice Chat 1.20.1-1.3.2
		roughlyenoughitems: Roughly Enough Items 12.0.630
			error_notifier: Error Notifier 1.0.9
		searchables: Searchables 1.0.1
		sodium: Sodium 0.4.10+build.27
		sodium-extra: Sodium Extra 0.4.20+mc1.20-build.103
			caffeineconfig: CaffeineConfig 1.1.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		soulfired: Soul fire'd 3.2.0.0
		sound_physics_remastered: Sound Physics Remastered 1.20.1-1.1.1
		stackrefill: Stack Refill 4.0
		swampier_swamps: Swampier Swamps 1.20-4.0.0
		terrablender: TerraBlender 3.0.0.167
			com_electronwill_night-config_core: core 3.6.4
			com_electronwill_night-config_toml: toml 3.6.4
		universalcraft: UniversalCraft 277
		usefulbackpacks: Useful Backpacks 2.0.1.121
		uteamcore: U Team Core 5.1.3.267
		vigilance: Vigilance 284
		visuality: Visuality 0.7.0+1.20
		voicechat: Simple Voice Chat 1.20.1-2.4.14
		windchimes: Windchimes 1.2.3+1.20
		xaerominimap: Xaero's Minimap 23.5.0
		xaeroworldmap: Xaero's World Map 1.30.6
		ydms_redpanda: YDM's Red Panda 1.0.4
	Loaded Shaderpack: §r§lAstra§4§lLex§r§l_By_LexBoosT_§4§lV79.0§r§l.zip
		Profile: Custom (+55 options changed by user)
	NEC status: No NEC detected
	Launched Version: fabric-loader-0.14.21-1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 2060/PCIe/SSE2 GL version 3.2.0 NVIDIA 536.40, NVIDIA Corporation
	Window size: 1800x900
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, fabric, file/swetrowe tekstury 2.3 - 1.20.x
	Current Language: en_us
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor

**Comment by TenKotowsky** [comment]
Nevermind, found out it already got fixed
